# Generated by Django 4.2.10 on 2025-04-16 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_boleta', models.CharField(max_length=100, verbose_name='Número de Boleta')),
                ('nombre_producto', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('codigo_producto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código del Producto')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('estado_devolucion', models.CharField(choices=[('devuelto', 'Devuelto en buen estado'), ('defectuoso', 'Producto defectuoso'), ('incompleto', 'Producto incompleto'), ('roto', 'Producto roto'), ('equivocado', 'Producto equivocado'), ('otro', 'Otro')], max_length=20, verbose_name='Estado de la Devolución')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('fecha_devolucion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Devolución')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
