# Generated by Django 4.2.10 on 2025-04-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='nota_credito',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Nota de Crédito'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='estado_devolucion',
            field=models.CharField(choices=[('normal', 'Normal (buen estado)'), ('mal_estado', 'Devolución (mal estado)'), ('pendiente_buen', 'Pendiente (buen estado)'), ('pendiente_mal', 'Pendiente (mal estado)'), ('otro', 'Otro')], max_length=20, verbose_name='Estado de la Devolución'),
        ),
    ]
