# Generated by Django 4.2.10 on 2025-04-17 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devoluciones_app', '0002_devolucion_fecha_cierre_devolucion_nota_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='marketplace',
            field=models.CharField(blank=True, choices=[('', 'Seleccione marketplace'), ('mercadolibre', 'Mercado Libre'), ('falabella', 'Falabella'), ('ripley', 'Ripley'), ('walmart', 'Walmart'), ('paris', 'Paris'), ('shopify', 'Shopify'), ('woocommerce', 'Woocommerce'), ('otro', 'Otro')], max_length=50, null=True, verbose_name='Marketplace'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='numero_orden',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Orden'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='porcentaje_pago',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Porcentaje de Pago'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='estado_devolucion',
            field=models.CharField(choices=[('normal', 'Normal (buen estado)'), ('mal_estado', 'Devolución (mal estado)'), ('pendiente_buen', 'Pendiente (buen estado)'), ('pendiente_mal', 'Pendiente (mal estado)'), ('extraviado', 'Extraviado'), ('otro', 'Otro')], max_length=20, verbose_name='Estado de la Devolución'),
        ),
    ]
